<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Jake" ignored="0" name="ValidateLogin" tests="1" failures="1" timestamp="23 Sep 2017 14:00:47 GMT" time="0.033" errors="0">
  <testcase name="Fail" time="0.016" classname="com.automation.inventorymanagement.EditProduct">
    <failure type="java.lang.AssertionError" message="expected [4] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [1]
	at com.automation.inventorymanagement.EditProduct.Fail(EditProduct.java:17)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Fail -->
</testsuite> <!-- ValidateLogin -->
